import cart from '../assets/images/cart.jpg';
import cart2 from '../assets/images/cart2.jpg';
import card3 from '../assets/images/card3.jpg';
import cart4 from '../assets/images/cart4.jpg';
import cart5 from '../assets/images/cart5.jpg';

const product = [
  {
    name: 'Vimto Squash Remix Apple 1.5...',
    id: 1,
    img: [card3, cart],
    price: 6.0,
    rating: 1,
    weight: 454,
    sku: '#VEG20957',
    type: 'Organic',
    Availability: 56,
  },
  {
    name: 'Taylors of Harrogate Yorkshi...',
    id: 2,
    img: [cart, cart],
    price: 10.5,
    rating: 1,
    weight: 200,
    sku: '#VEG20957',
    type: 'Organic',
    Availability: 56,
  },
  {
    name: 'Soft Mochi & Galeto Ice...',
    id: 3,
    img: [cart2, cart],
    price: 10.5,
    rating: 1,
    weight: 200,
    sku: '#VEG20957',
    type: 'Organic',
    Availability: 56,
  },
  {
    name: 'Naked Noodle Egg Noodles Sin...',
    id: 4,
    img: [cart4, cart],
    price: 10.5,
    rating: 1,
    weight: 500,
    sku: '#VEG20957',
    type: 'Organic',
    Availability: 56,
  },
  {
    name: 'Casillero Diablo Cabernet Sa...',
    id: 5,
    img: [card3, cart],
    price: 16.9,
    rating: 1,
    weight: 500,
    sku: '#VEG20957',
    type: 'Organic',
    Availability: 56,
  },
  {
    name: 'Taylors of Harrogate Yorkshi...',
    id: 6,
    img: [cart5, cart],
    price: 10.5,
    rating: 1,
    weight: 200,
    sku: '#VEG20957',
    type: 'Organic',
    Availability: 56,
  },
  {
    name: 'Soft Mochi & Galeto Ice...',
    id: 7,
    img: [cart2, cart],
    price: 10.5,
    rating: 1,
    weight: 200,
    sku: '#VEG20957',
    type: 'Organic',
    Availability: 56,
  },
  {
    name: 'Naked Noodle Egg Noodles Sin...',
    id: 8,
    img: [cart4, cart],
    price: 10.5,
    rating: 1,
    weight: 500,
    sku: '#VEG20957',
    type: 'Organic',
    Availability: 56,
  },
  {
    name: 'Casillero Diablo Cabernet Sa...',
    id: 9,
    img: [card3, cart],
    price: 16.9,
    rating: 1,
    weight: 500,
    sku: '#VEG20957',
    type: 'Organic',
    Availability: 56,
  },
];

export default product
